Add savings chart info hook
marsfoundation/spark-app pull request #329
Opened 2024-10-03 10:00 UTC by EmilMalanczak

2024-10-03 10:15 UTC, EmilMalanczak commented on packages/app/src/domain/savings-charts/useSavingsRateInfo/useSavingsRateInfo.ts
> +    queryFn: () => {
as I look right now - will move this into `savingsRateFilteredQueryOptions`

in general - this is using cached response for `savingsRate` but to prevent filtering with each rerender I've put into its own query key - by this we reduce amount of filtering with each timeframe change within selected timestamp (1h because data is updating once a day)

2024-10-03 10:21 UTC, EmilMalanczak commented on packages/app/src/domain/savings-charts/useSavingsRateInfo/useSavingsRateInfo.ts
> +    queryFn: () => {
also noticed lack of `staleTime` for both hooks

2024-10-03 12:22 UTC, yivlad commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/query.ts
> +export function myEarningsFilteredQueryOptions({
Why do we need to use react-query for filtering?

2024-10-03 12:22 UTC, yivlad commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/calculate-predictions.ts
> +  timestamp: number // in ms
We use pattern with naming `timestampInMs`

2024-10-03 12:22 UTC, yivlad commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/calculate-predictions.ts
> +        days: dataLength > 7 ? 3 : optimalPredictionsLength,
Isn't it basically the same as `Math.max(optimalPredictionsLength, 3)`? And I think it's much clearer

2024-10-03 12:22 UTC, yivlad commented on packages/app/src/domain/savings-charts/useSavingsChartsInfoQuery.ts
> +    staleTime: STEP_IN_MS,
Why do we need it?

2024-10-03 12:23 UTC, oskarvu commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/query.ts
> +      // balance is sum of sdai_balance and susds_balance but since we display it separately we can use balance
```suggestion
      // @note: response balance is a sum of sdai and usds balance, but we display chart only when user has only one token. Thus, we can treat this sum as a single token balance.
```

2024-10-03 12:23 UTC, oskarvu commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/query.ts
> +      assert(myEarningsInfo, 'My earnings info should be loaded before filtering')
skipToken

2024-10-03 12:23 UTC, oskarvu commented on packages/app/src/domain/savings-charts/useSavingsRateInfo/query.ts
> +      rate: z.string().transform((value) => NormalizedUnitNumber(value)),
Take a look at `packages/app/src/domain/common/validation.ts` and try to use it in your code. You can also add some validation there. For example this `rate: z.string().transform((value) => NormalizedUnitNumber(value))` could be just `rate: normalizedUnitNumberSchema`.

2024-10-03 12:41 UTC, EmilMalanczak commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/query.ts
> +export function myEarningsFilteredQueryOptions({
left a comment earlier but resolved it:

in general - didn't want to add `timeframe` dependency to the `myEarningsInfo` and `savingsRateInfo`

The data returned eg. `savingsRate` is containing data since 2019 so it's pretty large set of data. By passing filtering into the `select` function I would be forced to add `timeframe` to dependency. 

According to my research - `select` runs when: 
- query is first fetched
- query data is updated
- data is invalidated and refetched
 
 so to achieve update with each timeframe change we would have to download full data and put it into cache.

To prevent this I created separate query that takes the cached data so we download the data only once and by storing it into cache we reduce amount of filtering within selected timestamp (1h because data is updating once a day)

2024-10-03 12:45 UTC, EmilMalanczak commented on packages/app/src/domain/savings-charts/useSavingsChartsInfoQuery.ts
> +    staleTime: STEP_IN_MS,
This data is only updated once per day, so we can extend the `staleTime` beyond the default (which is like 1-2 minutes). Since we're dealing with large datasets that aren't updated frequently, there's no need to fetch them so often. Increasing the staleTime will help reduce unnecessary network requests and improve performance.

2024-10-03 12:47 UTC, yivlad commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/query.ts
> +export function myEarningsFilteredQueryOptions({
Select function also runs each time a newly created function instance is passed to `useQuery`, so for instance:
```ts
useQuery({
  ...,
  select: (data) => data
})
```
here select function will be run on every render. You can memoize select with useCallback but pass timeframe to dependency array.
```ts
useQuery({
  ...,
  select: useCallback((data) => filter(data, timeframe), [timeframe])
})
```

But anyway I think even simple useMemo would have worked.

2024-10-03 12:56 UTC, EmilMalanczak commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/calculate-predictions.ts
> +  timestamp: number // in ms
actually that should be `in seconds` wrong comment

2024-10-03 13:05 UTC, krzkaczor requested changes

2024-10-03 13:05 UTC, krzkaczor commented on packages/app/src/domain/savings-charts/useMyEarningsInfo/calculate-predictions.ts
> +  const dayIncomePrediction = NormalizedUnitNumber(
this can't be estimated this way since interests compounds

2024-10-04 06:49 UTC, krzkaczor approved these changes

2024-10-04 08:30 UTC, yivlad approved these changes

2024-10-04 08:30 UTC, yivlad commented on packages/app/src/utils/schemas.ts
> +export const dateSchema = z.string().transform((value) => new Date(value))
```suggestion
export const dateSchema = z.coerce.date()
```

2024-10-04 09:01 UTC, merged